plugins {
    id 'com.android.application'
}

def appVersionCode = project.hasProperty('customVersionCode') ? project.property('customVersionCode').toInteger() : 23
def appVersionName = project.hasProperty('customVersionName') ? project.property('customVersionName') : "1.1.19"

android {
    namespace 'com.aristotle.pos'
    compileSdk 34

    defaultConfig {
        applicationId "com.aristotle.pos"
        minSdk 24
        targetSdk 34
        versionCode appVersionCode
        versionName appVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
